### ISSUE TITLE
ModuleNotFoundError: No module named 'core.utils.download'

### ISSUE THREAD

**Issue by Harsh188** [shreyaskamathkm/FTNet#4]
## Description

There is no `core.utils.download` but it's being imported in the __init__.py file under `core/utils`.

## Log

```
Traceback (most recent call last):
  File "./../lightning_scripts/main.py", line 19, in <module>
    from trainers import thermal_edge_trainer
  File "/home/hmohan/Programming/T-SegModels/FTNet/Codes/src/lightning_scripts/trainers/__init__.py", line 1, in <module>
    from .thermal_edge_trainer import SegmentationLightningModel as thermal_edge_trainer
  File "/home/hmohan/Programming/T-SegModels/FTNet/Codes/src/lightning_scripts/trainers/thermal_edge_trainer.py", line 9, in <module>
    from .base_trainer import BaseTrainer
  File "/home/hmohan/Programming/T-SegModels/FTNet/Codes/src/lightning_scripts/trainers/base_trainer.py", line 26, in <module>
    from core.utils.json_extension import save_to_json_pretty
  File "/home/hmohan/Programming/T-SegModels/FTNet/Codes/src/core/utils/__init__.py", line 4, in <module>
    from .download import *
ModuleNotFoundError: No module named 'core.utils.download'
```

**Comment by shreyaskamathkm** [comment]
Can you retry once by commenting out that import?

**Comment by Harsh188** [comment]
Commenting out the import fixes the issue.
